# Альтернативный вариант с entrypoint скриптом
node-red:
  image: nodered/node-red:4.1
  container_name: node-red
  environment:
    - TZ=UTC
    - NODE_RED_ENABLE_SAFE_MODE=false
    - TENANT_DEFAULT=${TENANT_DEFAULT:-default}
    - WEBHOOK_SECRET=${WEBHOOK_SECRET:-change-me}
  volumes:
    - ./services/node-red/flows.json:/init/flows.json:ro
    - ./services/node-red/entrypoint.sh:/custom-entrypoint.sh:ro
    - node_red_data:/data
  entrypoint: ["/custom-entrypoint.sh"]
  depends_on:
    - traefik